### ISSUE TITLE
Don't understand HDC branch

### ISSUE THREAD

**Issue by zifeiyu-tan** [chaimi2013/CCM#1]
The input of CM is h*w*c, and two up-sampling is performed in the residual branch, while in the HDC branch, it seems that only one deconvolution is used at the end. So how do the two features add up?  .  In addition, what is the feature size of CM's output?

**Comment by zifeiyu-tan** [comment]
In addition, is there a plan to publish the code?

**Comment by chaimi2013** [comment]
> The input of CM is h_w_c, and two up-sampling is performed in the residual branch, while in the HDC branch, it seems that only one deconvolution is used at the end. So how do the two features add up? . In addition, what is the feature size of CM's output?

There is only one up-sampling operation in the residue branch, i.e., increasing the feature map size by two times.

**Comment by chaimi2013** [comment]
> In addition, is there a plan to publish the code?

The code will be released upon the publication of the paper.

**Comment by zifeiyu-tan** [comment]
> There is only one up-sampling operation in the residue branch, i.e., increasing the feature map size by two times.

Thank you for your work, so when the input of the CM branch is H*W*C, is the output of CM 2H*2W*C?  So is the size of the output heatmap different?

**Comment by zifeiyu-tan** [comment]
> > In addition, is there a plan to publish the code?
> 
> The code will be released upon the publication of the paper.

Thank you very much

**Comment by chaimi2013** [comment]
> H_2W_C

Yes. When there is a deconvolution layer in the CM, the spatial size of output feature maps is doubled.

**Comment by zifeiyu-tan** [comment]
> > H_2W_C
> 
> Yes. When there is a deconvolution layer in the CM, the spatial size of output feature maps is doubled.

Thanks, I understand.  Looking forward to your code announcement
